t_emma:
    resource: "@TEmmaBundle/Controller/"
    type:     annotation
login:
    path: "/login"
    defaults:  { _controller: TEmmaBundle:Secuity:login}
product_list:
    path: "/product/list"
    defaults:  { _controller: TEmmaBundle:Product:list}