mitarbeiter_index:
    path:     /
    defaults: { _controller: "TEmmaBundle:Mitarbeiter:index" }
    methods:  GET

mitarbeiter_show:
    path:     /{mitarbeiterid}/show
    defaults: { _controller: "TEmmaBundle:Mitarbeiter:show" }
    methods:  GET

mitarbeiter_new:
    path:     /new
    defaults: { _controller: "TEmmaBundle:Mitarbeiter:new" }
    methods:  [GET, POST]

mitarbeiter_edit:
    path:     /{mitarbeiterid}/edit
    defaults: { _controller: "TEmmaBundle:Mitarbeiter:edit" }
    methods:  [GET, POST]

mitarbeiter_delete:
    path:     /{mitarbeiterid}/delete
    defaults: { _controller: "TEmmaBundle:Mitarbeiter:delete" }
    methods:  DELETE
