t_emma_artikel:
    resource: "@TEmmaBundle/Resources/config/routing/artikel.yml"
    prefix:   /artikel
t_emma_mitarbeiter:
        resource: "@TEmmaBundle/Resources/config/routing/mitarbeiter.yml"
        prefix:   /mitarbeiter
t_emma_posten:
        resource: "@TEmmaBundle/Resources/config/routing/posten.yml"
        prefix:   /posten
t_emma_geschaeftsart:
        resource: "@TEmmaBundle/Resources/config/routing/geschaeftsart.yml"
        prefix:   /geschaeftsart
t_emma_geschaefte:
        resource: "@TEmmaBundle/Resources/config/routing/geschaefte.yml"
        prefix:   /geschaefte
t_emma_kunde:
        resource: "@TEmmaBundle/Resources/config/routing/kunde.yml"
        prefix:   /kunde
t_emma:
    path:   "/"
    defaults:  { _controller: TEmmaBundle:Default:index}
login:
    path: "/login"
    defaults:  { _controller: TEmmaBundle:Secuity:login}
t_emma_search:
    path: "/search/"
    defaults:  { _controller: TEmmaBundle:Default:search}