<?php

namespace TEmmaBundle\Repository;

/**
 * GeschaefteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeschaefteRepository extends \Doctrine\ORM\EntityRepository
{
}
