<?php

namespace TEmmaBundle\Repository;

/**
 * GeschaeftsartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeschaeftsartRepository extends \Doctrine\ORM\EntityRepository
{
}
